networks:
  laravel:
    name: laravel
services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - laravel
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
    container_name: mysql
    networks:
      - laravel
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: composer
    networks:
      - laravel
  # artisan:
  # npm:
volumes:
  mysql_data:
