networks:
  laravel:
    name: laravel
services:
  nginx:
    # image: "nginx:stable-alpine"
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - php
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    ports:
      - 3306:3306
    container_name: mysql
    networks:
      - laravel
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: composer
    networks:
      - laravel
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: artisan
    networks:
      - laravel
    entrypoint: ["php", "artisan"]
  npm:
    image: node:24.5-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    container_name: npm
    networks:
      - laravel
volumes:
  mysql_data:
