networks:
  laravel:
    name: laravel
services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - laravel
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php
    networks:
      - laravel
  # mysql:
  # composer:
  # artisan:
  # npm:
